module.exports.rules = {
	'no-param-reassign': require('./lib/rules/redefined/no-param-reassign'),
	'no-unused-expressions': require('./lib/rules/redefined/no-unused-expressions'),

	'abstract-class-name-prefix': require('./lib/rules/abstract-class-name-prefix'),
	'capitalized-enum': require('./lib/rules/capitalized-enum'),
	'capitalized-typedef': require('./lib/rules/capitalized-typedef'),
	'caps-const': require('./lib/rules/caps-const'),
	'event-const-desc': require('./lib/rules/event-const-desc'),
	'event-const-value': require('./lib/rules/event-const-value'),
	'interface-name-prefix': require('./lib/rules/interface-name-prefix'),
	'jsdoc-tags-order': require('./lib/rules/jsdoc-tags-order'),
	'jsdoc-type-application-dot': require('./lib/rules/jsdoc-type-application-dot'),
	'jsdoc-type-indent': require('./lib/rules/jsdoc-type-indent'),
	'jsdoc-type-spacing': require('./lib/rules/jsdoc-type-spacing'),
	'lines-around-class': require('./lib/rules/lines-around-class'),
	'lines-between-methods': require('./lib/rules/lines-between-methods'),
	'lines-between-props': require('./lib/rules/lines-between-props'),
	'methods-order': require('./lib/rules/methods-order'),
	'no-empty-method': require('./lib/rules/no-empty-method'),
	'no-jsdoc-type-multi-spaces': require('./lib/rules/no-jsdoc-type-multi-spaces'),
	'no-jsdoc-type-tabs': require('./lib/rules/no-jsdoc-type-tabs'),
	'no-public-underscore': require('./lib/rules/no-public-underscore'),
	'no-restricted-jsdoc-tags': require('./lib/rules/no-restricted-jsdoc-tags'),
	'prefer-shorthand-jsdoc-types': require('./lib/rules/prefer-shorthand-jsdoc-types'),
	'prevent-unused-jsdoc-types': require('./lib/rules/prevent-unused-jsdoc-types'),
	'prevent-unused-meta-params': require('./lib/rules/prevent-unused-meta-params'),
	'props-order': require('./lib/rules/props-order'),
	'singular-enum': require('./lib/rules/singular-enum'),
	'typecast-spacing': require('./lib/rules/typecast-spacing')
};
